#!/bin/sh
# -*- coding: utf-8-unix -*-
#
# チームで共通のGit hookを使う (https://www.farend.co.jp/blog/2020/04/git-hook/)
# <クローンしたときに１回だけ行う設定>
#   $ git config --local core.hooksPath .githooks
#   $ chmod -R +x .githooks/

# git rev : sample( v0.1.0-1-g4c048192 )
rev=`git describe --tags`
echo "# auto add version: $rev "

sed -i -e "s/\"version\":.*/\"version\":\"$rev\"/g" ./env.json
git add ./env.json

exit

